---

- name: Install node repository for apt
  apt_repository: repo='ppa:chris-lea/node.js' state=present

- name: Install sytem requirements via apt
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items: kibana_debian_requirements

- name: Link /usr/bin/node to /usr/bin/nodejs
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
