---
#In charge of rebuilding Kibana.
#This is called when either:
#   the git module reports a change
#   kibana_force_rebuild is overwritten to True
- name: Install npm modules
  command: chdir={{ kibana_git_clone_location }} npm install

- name: Install grunt-cli
  command: chdir={{ kibana_git_clone_location }} npm install -g grunt-cli

- name: Grunt build
  command: chdir={{ kibana_git_clone_location }} grunt build

- name: Update npm modules
  command: chdir={{ kibana_git_clone_location }} npm update

- name: Chown kibana directory
  file: path={{ kibana_location }} owner={{ kibana_user }} recurse=True state=directory

- name: Copy kibana into webroot
  synchronize: src={{ kibana_git_clone_location }}/src/ dest={{ kibana_location }}
  delegate_to: '{{ ansible_eth0.ipv4.address }}'

