---
- name: >
    RedHat | set_fact
      kibana_supported_os: True
  set_fact:
    kibana_supported_os: True

#TODO: Enable EPEL and install latest
- name: RedHat | Install git via yum
  yum: name={{ item }} state=present
  with_items: kibana_redhat_requirements