---
# handlers file for kibana

- name: Rebuild Kibana
  command: /bin/true
  notify:
    - Install npm modules
    - Install grunt-cli
    - Update npm modules
    - Grunt build
    - Chown kibana directory
    - Copy kibana into directory

- name: Install npm modules
  command: chdir={{ kibana_git_clone_location }} npm install

- name: Install grunt-cli
  command: chdir={{ kibana_git_clone_location }} npm install -g grunt-cli

- name: Grunt build
  command: chdir={{ kibana_git_clone_location }} grunt build

- name: Update npm modules
  command: chdir={{ kibana_git_clone_location }} npm update

- name: Chown kibana directory
  file: path={{ kibana_location }} owner={{ kibana_user }} recurse=True state=directory

#TODO: Clean up the copy function
- name: Copy kibana into directory
  command: rsync -avP {{ kibana_git_clone_location }}/src/ {{ kibana_location }}

- name: Reload nginx
  service: name=nginx state=reloaded

#- name: restart apache
#  service: >
#    name={{ apache_daemon }}
#    state=restarted